apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../backend/base
  - ../../monitor/base

  # versions

  # others
  - ../../frontend/base
  - ../../redis/base

  - ../../gateway/base
  - ../../network/base
