apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitor

resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- route.yaml
- serviceaccount.yaml
- policy.yaml

configMapGenerator:
- name: monitor-config
  literals:
  - VERSION=cilium_demo
  - DEMO_APP_HOST=http://192.168.254.230
